INSERT INTO vault_categories (slug, name_et, name_en, icon, sort_order, field_template) VALUES
('banking', 'Pangandus', 'Banking', '🏦', 1,
 '[{"key":"bank_name","label_et":"Panga nimi","label_en":"Bank name","type":"text","required":true},
   {"key":"account_number","label_et":"Konto number","label_en":"Account number","type":"text","required":true},
   {"key":"account_type","label_et":"Konto tüüp","label_en":"Account type","type":"select","options":["checking","savings","investment","credit"]},
   {"key":"online_banking_user","label_et":"Internetipanga kasutajanimi","label_en":"Online banking username","type":"text"},
   {"key":"contact_phone","label_et":"Panga kontakttelefon","label_en":"Bank contact phone","type":"text"}]'),

('insurance', 'Kindlustus', 'Insurance', '🛡️', 2,
 '[{"key":"provider","label_et":"Kindlustusandja","label_en":"Provider","type":"text","required":true},
   {"key":"policy_number","label_et":"Poliisi number","label_en":"Policy number","type":"text","required":true},
   {"key":"type","label_et":"Kindlustuse tüüp","label_en":"Insurance type","type":"select","options":["life","health","home","car","travel","other"]},
   {"key":"coverage_amount","label_et":"Kindlustussumma","label_en":"Coverage amount","type":"text"},
   {"key":"beneficiary","label_et":"Soodustatud isik","label_en":"Beneficiary","type":"text"},
   {"key":"renewal_date","label_et":"Uuendamise kuupäev","label_en":"Renewal date","type":"date"},
   {"key":"contact","label_et":"Kontakt","label_en":"Contact","type":"text"}]'),

('property', 'Kinnisvara', 'Property', '🏠', 3,
 '[{"key":"address","label_et":"Aadress","label_en":"Address","type":"text","required":true},
   {"key":"type","label_et":"Tüüp","label_en":"Type","type":"select","options":["apartment","house","land","commercial"]},
   {"key":"ownership","label_et":"Omandi osakaal","label_en":"Ownership share","type":"text"},
   {"key":"cadastral_number","label_et":"Katastri number","label_en":"Cadastral number","type":"text"},
   {"key":"mortgage_provider","label_et":"Laenuandja","label_en":"Mortgage provider","type":"text"},
   {"key":"mortgage_remaining","label_et":"Laenujääk","label_en":"Remaining mortgage","type":"text"}]'),

('digital_accounts', 'Digitaalsed kontod', 'Digital Accounts', '💻', 4,
 '[{"key":"service_name","label_et":"Teenuse nimi","label_en":"Service name","type":"text","required":true},
   {"key":"username","label_et":"Kasutajanimi","label_en":"Username","type":"text"},
   {"key":"email","label_et":"E-posti aadress","label_en":"Email","type":"text"},
   {"key":"url","label_et":"Veebiaadress","label_en":"URL","type":"text"},
   {"key":"action_after_death","label_et":"Tegevus pärast surma","label_en":"Action after death","type":"select","options":["delete","memorialize","transfer","close"]}]'),

('health', 'Tervis', 'Health', '❤️', 5,
 '[{"key":"doctor_name","label_et":"Arsti nimi","label_en":"Doctor name","type":"text"},
   {"key":"clinic","label_et":"Kliinik","label_en":"Clinic","type":"text"},
   {"key":"conditions","label_et":"Diagnoosid/seisundid","label_en":"Conditions","type":"textarea"},
   {"key":"medications","label_et":"Ravimid","label_en":"Medications","type":"textarea"},
   {"key":"allergies","label_et":"Allergiad","label_en":"Allergies","type":"textarea"},
   {"key":"blood_type","label_et":"Veregrupp","label_en":"Blood type","type":"select","options":["A+","A-","B+","B-","AB+","AB-","O+","O-","unknown"]},
   {"key":"organ_donor","label_et":"Doonorkaart","label_en":"Organ donor","type":"select","options":["yes","no","unknown"]}]'),

('legal', 'Õiguslikud dokumendid', 'Legal Documents', '⚖️', 6,
 '[{"key":"document_type","label_et":"Dokumendi tüüp","label_en":"Document type","type":"select","required":true,"options":["will","power_of_attorney","prenup","divorce_decree","court_order","contract","other"]},
   {"key":"created_date","label_et":"Koostamise kuupäev","label_en":"Created date","type":"date"},
   {"key":"notary","label_et":"Notar","label_en":"Notary","type":"text"},
   {"key":"location","label_et":"Asukoht (kus hoitakse)","label_en":"Location (where stored)","type":"text"},
   {"key":"notes","label_et":"Märkused","label_en":"Notes","type":"textarea"}]'),

('contracts', 'Lepingud ja tellimused', 'Contracts & Subscriptions', '📋', 7,
 '[{"key":"provider","label_et":"Teenusepakkuja","label_en":"Provider","type":"text","required":true},
   {"key":"type","label_et":"Tüüp","label_en":"Type","type":"select","options":["lease","loan","subscription","telecom","utility","other"]},
   {"key":"monthly_cost","label_et":"Kuumakse","label_en":"Monthly cost","type":"text"},
   {"key":"end_date","label_et":"Lõppkuupäev","label_en":"End date","type":"date"},
   {"key":"cancellation_method","label_et":"Tühistamise viis","label_en":"Cancellation method","type":"textarea"},
   {"key":"auto_renew","label_et":"Automaatne pikenemine","label_en":"Auto-renew","type":"select","options":["yes","no","unknown"]}]'),

('vehicles', 'Sõidukid', 'Vehicles', '🚗', 8,
 '[{"key":"make_model","label_et":"Mark ja mudel","label_en":"Make and model","type":"text","required":true},
   {"key":"reg_number","label_et":"Registreerimisnumber","label_en":"Registration number","type":"text"},
   {"key":"vin","label_et":"VIN kood","label_en":"VIN","type":"text"},
   {"key":"insurance_provider","label_et":"Kindlustus","label_en":"Insurance provider","type":"text"},
   {"key":"leasing_provider","label_et":"Liisinguandja","label_en":"Leasing provider","type":"text"}]'),

('personal_wishes', 'Isiklikud soovid', 'Personal Wishes', '🕊️', 9,
 '[{"key":"funeral_type","label_et":"Matuse tüüp","label_en":"Funeral type","type":"select","options":["burial","cremation","natural","other","no_preference"]},
   {"key":"funeral_location","label_et":"Matuse koht","label_en":"Funeral location","type":"text"},
   {"key":"music","label_et":"Muusika matustel","label_en":"Music at funeral","type":"textarea"},
   {"key":"message","label_et":"Sõnum lähedastele","label_en":"Message to loved ones","type":"textarea"},
   {"key":"special_instructions","label_et":"Erilised soovid","label_en":"Special instructions","type":"textarea"}]'),

('important_contacts', 'Olulised kontaktid', 'Important Contacts', '📞', 10,
 '[{"key":"name","label_et":"Nimi","label_en":"Name","type":"text","required":true},
   {"key":"role","label_et":"Roll","label_en":"Role","type":"select","options":["lawyer","accountant","financial_advisor","doctor","employer","landlord","other"]},
   {"key":"phone","label_et":"Telefon","label_en":"Phone","type":"text"},
   {"key":"email","label_et":"E-post","label_en":"Email","type":"text"},
   {"key":"notes","label_et":"Märkused","label_en":"Notes","type":"textarea"}]');
